# fly.toml app configuration file generated for griotai on 2023-06-30T14:11:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "griotai"
primary_region = "jnb"
kill_signal = "SIGINT"
kill_timeout = "5s"

[processes]
  web = "node server.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["web"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 550
    soft_limit = 500
